### GET request to get all patients
GET http://eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3OTcyNTQ2OCwiZXhwIjoxNzc5NzYxNDY4fQ/api/patients

#GET localhost:4000/patients đã đóng port của patient-service nên không dùng nữa
#GET localhost:4004/api/patients
Authorization: Bearer {{token}}
###